name: CI

on:
  push:
    branches: [ master, ci-test ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        name: [ production ]

    name: ${{ matrix.os }}:${{ matrix.name }}
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Install Packages
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libgmp-dev
    - name: Install Packages (MacOS)
      if: runner.os == 'macOS'
      run: |
        brew install \
          gmp
    - name: Setup Build Dir
      run: mkdir build
    - name: Configure
      run: cmake ..
      working-directory: build
    - name: Build
      run: make -j2
      working-directory: build
    - name: Test
      run: ctest --output-on-failure
      working-directory: build
