name: CI

on:
  push:
    branches: [ main, devel/cmake ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        name: [ production, debug ]

    name: ${{ matrix.os }}:${{ matrix.name }}
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Install Packages
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libgmp-dev
    - name: Install Packages (MacOS)
      if: runner.os == 'macOS'
      run: |
        brew install \
          gmp
    - name: Setup Build Dir
      run: mkdir build
    - name: Configure
      if: matrix.name == 'production'
      run: cmake -DCMAKE_BUILD_TYPE=Release ..
      working-directory: build
    - name: Configure
      if: matrix.name == 'debug'
      run: cmake -DCMAKE_BUILD_TYPE=Debug ..
      working-directory: build
    - name: Build
      run: make -j2
      working-directory: build
    - name: Test
      run: ctest --output-on-failure
      working-directory: build
